on:
  workflow_dispatch

name: Check README.md format
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check README.md format
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - run: |
          bash -x
          cd ./master
          GREP=$(grep '[A-Z]' README.md)
          if [ -z "$GREP" ]; then
            echo "No uppercase characters detected"
            exit 0
          else
            echo "Uppercase characters detected!" 
            exit 1
          fi
