on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'

name: Update Github Pages
jobs:
  update-ghpages:
    runs-on: ubuntu-latest
    name: Update Github Pages
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: master
          path: master
      - name: Checkout ghpages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - name: Check if github pages must be update    
        run: |
          cd ./master
          CHECK=$(git show --stat --oneline HEAD | cat | grep README.md)
          if [ ! -z "$CHECK" ]; then 
            echo "Update not necessary. README.md file not modified"
            exit 0
          else
            echo "Update necessary. README.md file modified"
          fi
          cd ../
      - name: Update github pages
        run: |
          cd ./master
          HASH=$(git log -n 1 --pretty=format:"%h")
          cd ..
          cp ./master/README.md ./gh-pages/index.md
          cd ./gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "synch with the $HASH commit from master branch"
          git push
